### ISSUE TITLE
Need example DATUM structure for a struct with 3 fields

### ISSUE THREAD

**Issue by rahpal** [Hyperion-BT/Helios#10]
spending matching_pubKeyHash
          struct Datum {
            owner: PubKeyHash
            nonce: Int
          }
          struct Redeemer {
            owner: PubKeyHash
            nonce: Int
          }
          func main(datum : Datum, redeemer: Redeemer) -> Bool {
            now: Int = 42;
            datum.owner == redeemer.owner && now < datum.nonce && now > redeemer.nonce
          }
          
          Need datum struct for validator to serialize properly???

**Comment by rahpal** [comment]
const datum = Data.to(
      new Constr(0, [new Constr(0, [paymentCredential?.hash!]), new Constr(1, [23n])])
    );
   
   This is how i am constructing my datum

**Comment by christianschmitz** [comment]
The Helios API supports generating Datums using only Helios (I'm still working on the documentation):

Your modified source (note MY_DATUM at the bottom):
```
spending matching_pubKeyHash

struct Datum {
  owner: PubKeyHash
  nonce: Int
}

struct Redeemer {
  owner: PubKeyHash
  nonce: Int
}

func main(datum : Datum, redeemer: Redeemer) -> Bool {
  now: Int = 42;
  datum.owner == redeemer.owner && now < datum.nonce && now > redeemer.nonce
}

const MY_DATUM = Datum{
    owner: PubKeyHash::new(#...),
    nonce: ...
}
```

And then in javascript you can call: 
```
let program = new helios.Program(src);
let datum_data_schema = program.evalParam("MY_DATUM").data.toSchemaJson()
```

**Comment by gs-rpal** [comment]
i am using lucid along with Helios. Need an example wrt lucid construct.. If you can help me ???

**Comment by rahpal** [comment]
i am using lucid along with Helios. Need an example wrt lucid construct.. If you can help me ???

**Comment by rahpal** [comment]
Moreover, i tried with method which you suggested. Datum is fine but unable to get redeemer form. 
`Redeemer (Spend, 0): The provided Plutus code called 'error'`

**Comment by christianschmitz** [comment]
I'm sorry, I have no experience with Lucid.

I suggest you inspect the `datum_data_schema` generated using Helios, and then try to build the same using `Data`/`Constr`/etc. in Lucid.

**Comment by christianschmitz** [comment]
> Moreover, i tried with method which you suggested. Datum is fine but unable to get redeemer form. `Redeemer (Spend, 0): The provided Plutus code called 'error'`

That is likely due to the way you programmed the condition in `main` (even though it looks like it returns `false`, the actually throws an error when validation fails).

You can try with the following Datum and Redeemer instead:
```
const MY_DATUM = Datum {
    owner: PubKeyHash::new(#...),
    nonce: 43
}

const MY_REDEEMER = Redeemer {
    owner: PubKeyHash::new(#...),
    nonce: 41
}
```

**Comment by rahpal** [comment]
Yep. Plutus code seems ok for me. Thanks anyways
