### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by christianschmitz** [Hyperion-BT/Helios#15]
In this issue we will tackle the design of *import* functionality in Helios.

**Comment by christianschmitz** [comment]
First syntax of imports should be decided:

Some ideas:
* `import OldName as NewName from "module-name"`
* `use OldName as NewName from "module-name"`

**Comment by christianschmitz** [comment]
**Syntax**

The following twitter poll is showing a preference for a Javascript-style import statement: https://twitter.com/helios_lang/status/1584911778340806656

I think it would be good to go along with this as it probably is one of the most recognizable syntaxes for import statements (remember that many more people will be reading/auditing smart contracts than actually writing smart contracts).

The complete Javascript import syntax is documented here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import. We are not yet concerned with importing whole modules, and there won't be defaults.

Importing a single name could thus look like this:
```
import {A as AliasA} from module_name
```

I suggest using module names without quotes. A new script purpose `module` could be created and placed at the top of each module file (so can't import from `spending`/`minting`/`staking`/`testing` scripts). 
```
module my_module
```

The name that comes after the `module` keyword will also be the name needed after the `from` keyword when importing.

`main` and the name of the current main script should be forbidden names for modules.

Multiple imports from one module could be comma separated:
```
import {A as AliasA, B as AliasB} from module_name
```

And of course aliases are optional:
```
import {A, B as AliasB} from module_name
```

If just one name is imported, and no alias is specified, the braces are optional:
```
import A from module_name 
```

**Comment by christianschmitz** [comment]
**Syntax (cont)**

Import statements make the most sense at the top of each script, right after the script purpose header.

Helios however has two different semantics based on the location in the main script file:
   * **strict** in, and before, the `main` function
   * **non-strict** after the `main` function

So it makes sense to also allow imports after the `main` function. In order to avoid confusion I suggest allowing imports anywhere in the top-level scope of a Helios source.

**Comment by christianschmitz** [comment]
**Changes to API**

Currently compilation using the Helios library looks as follows:
```ts
helios.Program.new(src: string).compile(): helios.UplcProgram
```

I suggest adding a list of module sources as a second optional argument:
```ts
helios.Program.new(src: string, modules: string[]).compile(): helios.UplcProgram
```

`evalParam` and `changeParam` will only be able to evaluate/change `const` statements in the main source, not in the modules. Importing constants into the main script will though be enough to make them available for evaluating/changing.

**Comment by novadev94** [comment]
That’s a very in-depth proposal. Almost all of them look great to me. 

I’d like to discuss these 2 things a little bit more:

- Shortcut for importing single member might not be needed. Depending on the next point.

- I'm afraid strict modules might be too strict (if I understand it correctly).
  + That would effectively disable having multiple non-dependent members in modules, and force devs to go towards "unit module" - where there's only 1 exported member per module. It's like "if you want to import something, you also need to import everything else in that module".
  + It's an even bigger problem with methods since we haven't lifted the strict restrictions for them yet (just the fields). So devs are forced to have 1 module for just the struct/enum, and N modules for the methods/functions.

We can also separate the compile and link steps but definitely not necessary at the moment.

Btw, I don't fully understand this phrase, could you please elaborate?
> as it centralizes the standard library (i.e. the Helios builtins)

**Comment by christianschmitz** [comment]
Opening up imports allows the creation of third party libraries, and then those functions could start deviating from the Helios builtins (it will be easier for developers to start writing their own library functions, instead of contacting me and having a proper discussion about the utility/security of a given library method).

**Comment by christianschmitz** [comment]
>     * I'm afraid strict modules might be too strict (if I understand it correctly). That would effectively disable having multiple non-dependent members in modules, and force devs to go towards "unit module" - where there's only 1 exported member per module. It's like "if you want to use something, you also need to use everything else in that module".

I also feel I'm being too restrictive. An alternative approach could be to allow unused top-level statements everywhere (in modules as well as in the main scripts), and have a special clean-up API method remove the unused code for audit purpose.

I've implemented this in the *modules* branch, the method is called `program.cleanSource()`. Have a look at the `test-syntax.js` file in the *modules* branch to see it in action.

**Comment by novadev94** [comment]
Great idea! That's balanced between DX and keeping Helios SCs easily auditable.

**Comment by christianschmitz** [comment]
Done as of v0.8.9
