### ISSUE TITLE
`NetworkParams::timeToSlot` - Giving wrong slot

### ISSUE THREAD

**Issue by gavinharris-dev** [Hyperion-BT/Helios#17]
`NetworkParams::timeToSlot` Looks like the Time diff calc is backwards? 

Current: 
`let timeDiff = lastTime - time;`
Should it be: 
`let timeDiff = time - lastTime;`

**Based on existing logic:** 
slot = 11144921
time = 1666828121

currentTime = 1666852019000 (this was true when I raised)

secondsPerSlot = 1
lastSlot = 11144921
lastTime = 1666828121 * 1000 = 1666828121000

timeDiff = 1666828121000 - 1666852019000

Result: lastSlot + (timeDiff / (1000 * secordsPerSlot) or
  11144921 + ( -23898000 ) / (1000 * 1)

Result: 11121023
Expect: 11168819

https://github.com/Hyperion-BT/Helios/blob/main/helios.js#L3172

**Comment by christianschmitz** [comment]
You're completely right. Library has been update -> v0.8.3
