### ISSUE TITLE
ScriptContext.now() is undefined

### ISSUE THREAD

**Issue by thaddeusdiamond** [Hyperion-BT/Helios#2]
I am attempting to do some sample Helios scripting and deploy it to Preprod.  I am looking into the minting policy scripting as found in [Helios Book Chapter 3](https://hyperion-bt.github.io/Helios-Book/chapter_3/NFT.html).  When I use Helios v0.6.5 (either from compiling into my source code in `npm` or using the playground as in the attached photo) I get the following error:

```
ReferenceError on line 6: ScriptContext.now undefined
```

Please advise on how to proceed. 

<img width="1784" alt="Screen Shot 2022-09-27 at 10 44 30 AM" src="https://user-images.githubusercontent.com/648325/192573288-1c6535c1-4d27-4750-85aa-252e8ef18a15.png">

**Comment by thaddeusdiamond** [comment]
Looks like the `ScriptContext` object does not have the `now()` method the Tx does:
https://hyperion-bt.github.io/Helios-Book/chapter_2/03_ScriptContext.html

Looks to be a doc fix for chapter 3.

**Comment by christianschmitz** [comment]
Where did you see that `now` was a member of `ScriptContext`?

**Comment by thaddeusdiamond** [comment]
The first link (chapter 3).

**Comment by christianschmitz** [comment]
I've corrected the documentation.

If you are happy with the changes I will close this issue

Next time issues with the documentation should probably be posted under the [Helios-Book](https://github.com/Hyperion-BT/Helios-Book) repository instead.

**Comment by thaddeusdiamond** [comment]
Will do thanks!
