### ISSUE TITLE
Reference Inputs - Requires a full TxInput

### ISSUE THREAD

**Issue by gavinharris-dev** [Hyperion-BT/Helios#21]
With regards to Reference Inputs, should the API only require the `TxId` and Index?

Currently `addRefInput` requires a full TxInput object, however these inputs are not needed for balancing a transaction and so the need for a full TxInput is moot. I'm wondering if there could be a TxRefInput class that only requires the TxId and Transaction Index?

Worth a PR?

**Comment by gavinharris-dev** [comment]
I wonder if something as 'simple' as work?

```
export class TxRefInput extends TxInput {
	/**
	 * @param {Hash} txId 
	 * @param {bigint} utxoIdx
	 */
	 constructor(txId, utxoIdx) {
		super(txId, utxoIdx, null);
	}
}
```

**Comment by christianschmitz** [comment]
Perfect solution! Will quickly add it for you

**Comment by christianschmitz** [comment]
done -> v0.8.6
