### ISSUE TITLE
Support Staking Addresses

### ISSUE THREAD

**Issue by gavinharris-dev** [Hyperion-BT/Helios#29]
It would be great to be able to have a `toStakeAddress` method on Address to support https://cips.cardano.org/cips/cip19/#stakeaddresses.

**Comment by christianschmitz** [comment]
Or alternatively a `StakeAddress` class?

How do StakeAddresses differ from regular addresses with a delegation part though?

**Comment by gavinharris-dev** [comment]
I'm not sure a separate class is needed, perhaps it is just not thought enough about it yet! Sorry!

With respect to the difference, a Staking Address does not contain the Payment Credential; so the first part of a Shelly Address. 
A Staking Address can be used to reference all assets (ADA and Tokens) thought to be under control (available to be staked) by the owner of said Stake Address. Therefore it would be feasible to place assets into Transaction and Cold Wallets and even into Script Addresses (say a vesting contract where you are still able to stake the ADA earning rewards while your ADA is vested); and using the Staking Address users and developers be able to reference all the Assets via this single Address.

References: 
https://cips.cardano.org/cips/cip19/#stakeaddresses
https://github.com/cardano-foundation/CIPs/tree/master/CIP-0005#about-stake

**Comment by christianschmitz** [comment]
Implemented as of v0.9.5

Docs: https://www.hyperion-bt.org/Helios-Book/api/reference/stakeaddress.html
