### ISSUE TITLE
ScriptContext argument causes headList Issue

### ISSUE THREAD

**Issue by thaddeusdiamond** [Hyperion-BT/Helios#3]
The following script on Helios v0.6.5 executes in Phase 1 fine:

```
  minting voting_ballot

  enum Redeemer {
    Mint
  }

  func main(redeemer: Redeemer) -> Bool {
    redeemer.switch {
      Mint =>  {
        print("abc");
        true
      }
    }
  }
```

But the following causes an issue:

```
  minting voting_ballot

  enum Redeemer {
    Mint
  }

  func main(redeemer: Redeemer, ctx: ScriptContext) -> Bool {
    redeemer.switch {
      Mint =>  {
        print("abc");
        print(ctx.tx.now().show());
        true
      }
    }
  }
```

Specifically, Phase 1 throws the error:

```
{
 "ScriptFailures": {
 "mint:0": [
 {
 "validatorFailed": {
 "error": "An error has occurred: User error:\
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.\
Caused by: [ (force (builtin headList)) (con list (data) []) ]",
 "traces": [
 "abc"
 ]
 }
 }
 ]
 }
}
```

**Comment by christianschmitz** [comment]
`now()` uses the start of the valid `time_range` as an indirect way to calculate the current time.

I think the error is probably thrown due to the runtime structure of `tx.time_range`.
If you don't use the cardano-cli `--invalid-before <current-slot-no>` option then the valid `time_range` is -inf to +inf. And then the `now()` function throws error because it can't get the current time from start of the `time_range`.

Sadly there is no direct way of getting the current time.

I will update the documentation to explain this, and I'm also considering automatically included the current slot for the valid `time_range` when building transaction using Helios.

**Comment by christianschmitz** [comment]
What is really is annoying is that when building the tx you have to specify the slot-number, but when validating the script sees posix time (milliseconds since 01/01/1970).

I'm sorry about this weird cardano-ism, but not much we can do about it.

**Comment by thaddeusdiamond** [comment]
No worries.  Any recommendation on getting the current slot of the txn to validate the time range? I am trying to build an on-chain minting policy and have ppl construct the tx on web using Lucid, so doing this via Javascript compilation is the preferred method.  I can pre-compile the CBOR using Helios Lang on cardano-cli and then upload to JS if that's the only way.

**Comment by christianschmitz** [comment]
I don't know if Lucid has that capability yet.

However you can actually build transactions using Helios. There are some examples in https://github.com/Hyperion-BT/PicoSwap/blob/main/index.js (eg. the buyContract function). You can use the `Tx.setInvalifBefore(<slot-no>)` method.

What I usually do for the conversion is downloading a recent Blockchain state (which will contain the current slot number), and add 1 slot per second when using that info after the moment you downloaded it. When I have time I will make it so it happens automatically in the background.

**Comment by thaddeusdiamond** [comment]
Gotcha.  I actually was looking more for the comparison to occur on-chain.  Do you have an analogue to `txInfoValidRange` from the Plutus Core type? That way I can just check that the txn's valid range is inside of the mint interval using a time comparison. Sorry for the roundabout question.

`TxInfo` Definition:
https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger-api/html/Plutus-V1-Ledger-Contexts.html

**Comment by christianschmitz** [comment]
`ctx.tx.time_range` I think, which returns a value of `TimeRange` type. The docs describe some basic builtin methods for `TimeRange`

**Comment by thaddeusdiamond** [comment]
The following Helios code:

```
minting voting_ballot

const POLLS_CLOSE: Time = Time::new(1666242000000) // 10/20/22 00:00:00

enum Redeemer {
  Mint
}

func main(redeemer: Redeemer, ctx: ScriptContext) -> Bool {
  redeemer.switch {
    Mint =>  {
      tx: Tx = ctx.tx;

      tx_valid: Bool = tx.time_range.is_after(POLLS_CLOSE);
      time_range_valid_msg: String = if (tx_valid) { "Valid" } else { "Invalid" };

      print(time_range_valid_msg + " time range: " + tx.time_range.serialize().show());
      tx_valid
    }
  }
}
```

Combined with the following Lucid code:

```
    const assetId = `${lucid.utils.mintingPolicyToId(MINTING_SCRIPT)}${assetName}`;
    const mintAssets = { [assetId]: SINGLE_NFT };
    const vendAssets = { lovelace: 2n, [assetId]: SINGLE_NFT };
    const txBuilder = lucid.newTx()
                           .addSigner(voter)
                           .mintAssets(mintAssets, Data.empty())
                           .attachMintingPolicy(MINTING_SCRIPT)
                           .payToAddress(voter, vendAssets);
    const txComplete = await txBuilder.complete();
    const txSigned = await txComplete.sign().complete();
    const txHash = await txSigned.submit();
    shortToast(`Successfully submitted ${txHash}`);```

Successfully shows the invalid trace:

```
{
 "ScriptFailures": {
 "mint:0": [
 {
 "validatorFailed": {
 "error": "An error has occurred: User error:\
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.",
 "traces": [
 "Invalid time range: d8799fd8799fd87980d87a80ffd8799fd87b80d87a80ffff"
 ]
 }
 }
 ]
 }
}
```

However, when I add a tx bounds (using Lucid's `validTo(1666242000000 - 1)` and `validFrom(1664462000000)` method) I get the following error:

```
{
 "CannotCreateEvaluationContext": {
 "reason": "Uncomputable slot arithmetic; transaction's validity bounds go beyond the foreseeable end of the current era: PastHorizon {pastHorizonCallStack = [(\\"runQuery\\",SrcLoc {srcLocPackage = \\"ouroboros-consensus-0.1.0.0-49JPZHi3BBPHYH0tX8EuCK\\", srcLocModule = \\"Ouroboros.Consensus.HardFork.History.Qry\\", srcLocFile = \\"src/Ouroboros/Consensus/HardFork/History/Qry.hs\\", srcLocStartLine = 430, srcLocStartCol = 44, srcLocEndLine = 430, srcLocEndCol = 64}),(\\"interpretQuery\\",SrcLoc {srcLocPackage = \\"ouroboros-consensus-0.1.0.0-49JPZHi3BBPHYH0tX8EuCK\\", srcLocModule = \\"Ouroboros.Consensus.HardFork.History.EpochInfo\\", srcLocFile = \\"src/Ouroboros/Consensus/HardFork/History/EpochInfo.hs\\", srcLocStartLine = 45, srcLocStartCol = 50, srcLocEndLine = 45, srcLocEndCol = 68}),(\\"interpretQuery'\\",SrcLoc {srcLocPackage = \\"ouroboros-consensus-0.1.0.0-49JPZHi3BBPHYH0tX8EuCK\\", srcLocModule = \\"Ouroboros.Consensus.HardFork.History.EpochInfo\\", srcLocFile = \\"src/Ouroboros/Consensus/HardFork/History/EpochInfo.hs\\", srcLocStartLine = 39, srcLocStartCol = 9, srcLocEndLine = 39, srcLocEndCol = 52}),(\\"epochInfoSlotToRelativeTime_\\",SrcLoc {srcLocPackage = \\"cardano-slotting-0.1.0.0-2TqNOMpwMGu2Ao1epk6Blc\\", srcLocModule = \\"Cardano.Slotting.EpochInfo.API\\", srcLocFile = \\"src/Cardano/Slotting/EpochInfo/API.hs\\", srcLocStartLine = 62, srcLocStartCol = 9, srcLocEndLine = 62, srcLocEndCol = 37}),(\\"epochInfoSlotToRelativeTime\\",SrcLoc {srcLocPackage = \\"cardano-slotting-0.1.0.0-2TqNOMpwMGu2Ao1epk6Blc\\", srcLocModule = \\"Cardano.Slotting.EpochInfo.API\\", srcLocFile = \\"src/Cardano/Slotting/EpochInfo/API.hs\\", srcLocStartLine = 125, srcLocStartCol = 40, srcLocEndLine = 125, srcLocEndCol = 70}),(\\"epochInfoSlotToRelativeTime_\\",SrcLoc {srcLocPackage = \\"cardano-slotting-0.1.0.0-2TqNOMpwMGu2Ao1epk6Blc\\", srcLocModule = \\"Cardano.Slotting.EpochInfo.API\\", srcLocFile = \\"src/Cardano/Slotting/EpochInfo/API.hs\\", srcLocStartLine = 62, srcLocStartCol = 9, srcLocEndLine = 62, srcLocEndCol = 37}),(\\"epochInfoSlotToRelativeTime\\",SrcLoc {srcLocPackage = \\"cardano-slotting-0.1.0.0-2TqNOMpwMGu2Ao1epk6Blc\\", srcLocModule = \\"Cardano.Slotting.EpochInfo.API\\", srcLocFile = \\"src/Cardano/Slotting/EpochInfo/API.hs\\", srcLocStartLine = 91, srcLocStartCol = 30, srcLocEndLine = 91, srcLocEndCol = 63}),(\\"epochInfoSlotToUTCTime\\",SrcLoc {srcLocPackage = \\"cardano-ledger-alonzo-0.1.0.0-9cAkjk5gmSd7zINSOWDoNC\\", srcLocModule = \\"Cardano.Ledger.Alonzo.TxInfo\\", srcLocFile = \\"src/Cardano/Ledger/Alonzo/TxInfo.hs\\", srcLocStartLine = 233, srcLocStartCol = 9, srcLocEndLine = 233, srcLocEndCol = 41})], pastHorizonExpression = Some (EPair (ERelToAbsTime (ERelSlotToTime (EAbsToRelSlot (ELit (SlotNo 74675709))))) (ESlotLength (ELit (SlotNo 74675709)))), pastHorizonSummary = [EraSummary {eraStart = Bound {boundTime = RelativeTime 0s, boundSlot = SlotNo 0, boundEpoch = EpochNo 0}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 89856000s, boundSlot = SlotNo 4492800, boundEpoch = EpochNo 208}), eraParams = EraParams {eraEpochSize = EpochSize 21600, eraSlotLength = SlotLength 20s, eraSafeZone = StandardSafeZone 4320}},EraSummary {eraStart = Bound {boundTime = RelativeTime 89856000s, boundSlot = SlotNo 4492800, boundEpoch = EpochNo 208}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 101952000s, boundSlot = SlotNo 16588800, boundEpoch = EpochNo 236}), eraParams = EraParams {eraEpochSize = EpochSize 432000, eraSlotLength = SlotLength 1s, eraSafeZone = StandardSafeZone 129600}},EraSummary {eraStart = Bound {boundTime = RelativeTime 101952000s, boundSlot = SlotNo 16588800, boundEpoch = EpochNo 236}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 108432000s, boundSlot = SlotNo 23068800, boundEpoch = EpochNo 251}), eraParams = EraParams {eraEpochSize = EpochSize 432000, eraSlotLength = SlotLength 1s, eraSafeZone = StandardSafeZone 129600}},EraSummary {eraStart = Bound {boundTime = RelativeTime 108432000s, boundSlot = SlotNo 23068800, boundEpoch = EpochNo 251}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 125280000s, boundSlot = SlotNo 39916800, boundEpoch = EpochNo 290}), eraParams = EraParams {eraEpochSize = EpochSize 432000, eraSlotLength = SlotLength 1s, eraSafeZone = StandardSafeZone 129600}},EraSummary {eraStart = Bound {boundTime = RelativeTime 125280000s, boundSlot = SlotNo 39916800, boundEpoch = EpochNo 290}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 157680000s, boundSlot = SlotNo 72316800, boundEpoch = EpochNo 365}), eraParams = EraParams {eraEpochSize = EpochSize 432000, eraSlotLength = SlotLength 1s, eraSafeZone = StandardSafeZone 129600}},EraSummary {eraStart = Bound {boundTime = RelativeTime 157680000s, boundSlot = SlotNo 72316800, boundEpoch = EpochNo 365}, eraEnd = EraEnd (Bound {boundTime = RelativeTime 158544000s, boundSlot = SlotNo 73180800, boundEpoch = EpochNo 367}), eraParams = EraParams {eraEpochSize = EpochSize 432000, eraSlotLength = SlotLength 1s, eraSafeZone = StandardSafeZone 129600}}]}"
 }
}
```

Note that constructing the Lucid transaction *without* the plutus minting policy and using this validity interval does successfully work.  Any thoughts? Thanks for all your patience and help

**Comment by thaddeusdiamond** [comment]
I will open a documentation issue.  The wording on `is_before` and `is_after` is very confusing so I was doing the wrong function call.  The correct Helios code to make this work was:

```

  minting voting_ballot

  const POLLS_CLOSE: Time = Time::new(1666242000000) // 10/20/22 00:00:00

  enum Redeemer {
    Mint
  }

  func main(redeemer: Redeemer, ctx: ScriptContext) -> Bool {
    redeemer.switch {
      Mint =>  {
        tx: Tx = ctx.tx;

        tx_valid: Bool = tx.time_range.is_before(POLLS_CLOSE);
        time_range_valid_msg: String = if (tx_valid) { "Valid" } else { "Invalid" };

        print(time_range_valid_msg + " time range: " + tx.time_range.serialize().show());
        tx_valid
      }
    }
  }
```
