### ISSUE TITLE
Type-safe way to construct/deconstruct Datum/Redeemer

### ISSUE THREAD

**Issue by sk-shishi** [Hyperion-BT/Helios#33]
Currently:
* The recommended way for Datum/Redeemer construction is using `evalParam` - which is quite verbose, especially for enum types.
* There's no straightforward way for deconstruction - which is useful for chain indexing.

This problem can be split into 2 smaller ones:
1. Way to construct/deconstruct in a type-safe way, given the schema is available.
2. Synchronize the schema and Helios type definitions.

For the (1) problem, Lucid had some recent successes with `typebox`
https://github.com/spacebudz/lucid/blob/main/src/plutus/data.ts
https://github.com/spacebudz/lucid/blob/main/tests/data.test.ts

I personally gave it a try, it works quite well. The only problem is it's not compatible with how Helios is encoding structs (data-lists).

**Comment by christianschmitz** [comment]
For construction I was thinking the following:

`program.types` contain javascript equivalents of all the types that are accessible in the top-scope of the main script.

Eg. `program.types.MyStruct`

Then instantiating would be like a regular javascript class: `const {MyStruct} = new program.types; const my_instance = new MyStruct(...)`

The fields of `MyStruct` can either be something primitive (which is automatically converted to the correct DataType), or another Helios-to-javascript-equivalent instance.

For enums the constructable class could be one level deeper: `const {MyRedeemer} = program.types.MyRedeemer; const my_instance = new MyRedeemer.MyVariant(...)`

**Comment by christianschmitz** [comment]
Deconstruction could be similar to Helios: automatically defining a static `fromData` method for each helios-javascript-equivalent type.

**Comment by sk-shishi** [comment]
Your proposed solution sounds great to me. Just one extra question: Will the TS-type interfaces be auto-generated too? I'm afraid it might not be feasible with dynamic runtime types - so maybe we need some codegen here?

**Comment by christianschmitz** [comment]
What do you mean by codegen? Like a build step that creates type-definitions?

How would you like to run the codegen? Using the helios cli and a file-listener?

**Comment by sk-shishi** [comment]
> What do you mean by codegen? Like a build step that creates type-definitions?

Yes.

> How would you like to run the codegen? Using the helios cli and a file-listener?

I'm fine with having to run `helios-cli` every time the types are changed. During development, having file listened would be good - but it can be done externally by the devs, we can just leave some docs.

**Comment by christianschmitz** [comment]
This feature is now available (v0.10.6).

To get an object containing all the user-defined types:
`program.types`

To construct a struct:
`new program.types.MyStruct(field1, field2, ...)`

To construct an enum:
`new program.types.MyEnum.MyVariant(field1, ...)`

To use a constructed value as script parameter:
`program.parameters = {MY_PARAM: myValue}`

`program.parameters` returns an object containing all the current parameter values as instances similar to these user-type instances.

Only the following builtin types are supported: Int, Time, Duration, Bool, ByteArray, HeliosString,  List, Option, HeliosMap, Address, TxId, TxOutputId, Value, StakingValidatorHash, PubKeyHash, ValidatorHash, StakeKeyHash, DatumHash
