### ISSUE TITLE
Seems there is no way to add Collateral Return

### ISSUE THREAD

**Issue by gavinharris-dev** [Hyperion-BT/helios#43]
With the Vasil hardfork it became possible to include a TxOut that is used if Collateral is claimed (i.e., a TX fails on the node). 

Pre-Vasil we would need to add a 'pure' UTxO (one not tainted with Tokens!), however with Collateral Return this is no longer a requirement!

It would be great if we could extend the `tx::finalize' method to calculate the Collateral amount for the transaction. I believe it is calculated as Transaction Fee multiplied by 150%.  One point to remember, adding Collateral Return would increase the overall size of the TX and therefore change the Lovelace amount to be deducted! So perhaps it could be mocked in a similar way to Witnesses. 

Note: The 150% comes from a Protocol Parameter (`networkParams` parameter).

**Comment by christianschmitz** [comment]
I'm investigating how to do this automatically inside the finalization step, so DApp developers don't have to think about this.

**Comment by gavinharris-dev** [comment]
Yeah it would be amazing to get this put into the `finalize` method.

**Comment by christianschmitz** [comment]
v0.12.6 should automatically set the collateral inputs and create a collateral return, hopefully making everything automatic and convenient. Could you check that it works for your cases?

**Comment by christianschmitz** [comment]
Hopefully definitively resolved by v0.12.12

**Comment by gavinharris-dev** [comment]
Very much fixed now!
