### ISSUE TITLE
collateral utxo getting spent and tx.finalize() outputs

### ISSUE THREAD

**Issue by lley154** [Hyperion-BT/helios#44]
Hi Christian,  I’ve noticed some issues with the Tx Builder

 walletHelper.pickUtxos();

Issue #1 - The collateral is getting included in the general inputs and getting spent as part of a transaction.   I compared it with the direct walletAPI and confirmed that the collateral UTXO is not included in the set of spendable inputs.   So this is something specific to walletHelper.  See attached for utxo output comparison.

Tx.finalize();

Issue #2 - The issue is with how UTXOs are grouped when the tx is finalized.   What I am seeing is that all available Ada is grouped with native token(s) when possible.   The result is that there is no clean UTXO with just ada in it.   Attached is a good example from Nami when setting collateral, notice how Nami keeps Ada assigned to the tokens with small amounts and creates a large clean UTXO with only Ada.  

The only exception is that if an output is specifically created with let's say 10 ada + token, then the finalize should not make any changes to that output.  The discussion here should only apply to outputs that are created for change.

Helios v0.11.2
 
[utxos from Helios wallet helper.pdf](https://github.com/Hyperion-BT/helios/files/10735989/utxos.from.Helios.wallet.helper.pdf)

**Comment by MatthewDEVi** [comment]
@lley154 Talk to Cardano  Support on the [Cardano Live Support](https://explore-cardano.org/) so that your issue can be looked into.

**Comment by lley154** [comment]
> @lley154 Talk to Cardano Support on the [Cardano Live Support](https://explore-cardano.org/) so that your issue can be looked into.

I've been chatting with Christian on Helios discord and he is looking into the 2 issues above.

**Comment by MatthewDEVi** [comment]
kindly create chat with the support so your issue can be looked up to immediately

**Comment by christianschmitz** [comment]
Both issues should be fixed by v0.12.6. Could you check?

**Comment by lley154** [comment]
Hi Christian, goods and bad news.   I will close this issue because both of the issues #1 and #2 have been fixed - thank you!   Bad news, is that there are 2 new bugs related to #1 and #2 respectively.   I'll open a bug for each of them.

Issue #1 fixed evidence:
![image](https://user-images.githubusercontent.com/7105016/222528098-4dc36f81-4bfd-4c55-a7cd-f477a31b78b1.png)



Issue#2 fixed evidence:
![image](https://user-images.githubusercontent.com/7105016/222527447-21227566-9980-45ba-aaf4-03055141b95b.png)
