### ISSUE TITLE
fromCbor for UPLC Program

### ISSUE THREAD

**Issue by nielstron** [Hyperion-BT/helios#48]
I can't seem to find a method to deserialize a flat encoded UPLC program with helios. This would be a great feature to on-the-fly modify existing programs (i.e. parameterized scripts output by PlutusTx, aiken, etc)

**Comment by christianschmitz** [comment]
Thanks for noticing that this was missing from the docs. I've now documented the `fromCbor` method on the following page: https://www.hyperion-bt.org/helios-book/api/reference/uplcprogram.html

You can also work with the flat encoded UplcProgram directly: https://www.hyperion-bt.org/helios-book/api/reference/functions.html#deserializeuplcbytes

**Comment by christianschmitz** [comment]
(In a next commit of the library I might make all public `fromCbor` methods accept hexadecimal `string` or `number[] for convenience, currently you would have to use `helios.hexToBytes(...)`)
