### ISSUE TITLE
ctx.tx() is -0 even when using a proper validity_start_interval

### ISSUE THREAD

**Issue by rodrigomd94** [Hyperion-BT/Helios#5]
I am trying to use the vesting contract but when printing  `print(tx.now().show());` it show `-0`.
I have checked and the transaction does have a `"validity_start_interval": "8885283"` (preview network).
What could cause tx.now() beingequal to -0 ?

I get the same result on mainnet, and preprod.

**Comment by rodrigomd94** [comment]
The problem was resolved by disabling the native uplc compiler on Lucid. So completing the transaction with `.complete({nativeUplc:false})`

**Comment by christianschmitz** [comment]
Thanks for figuring this out!
