### ISSUE TITLE
Extending Helios to support destructuring

### ISSUE THREAD

**Issue by vanusquarm** [Hyperion-BT/helios#56]
![Helios](https://user-images.githubusercontent.com/35784409/221728072-6b1ec738-2276-4d46-83cf-369e5a05629c.PNG)
Extending Helios language constraint to support destructuring to allow the same operations as seen in the image to generate the same results without errors. This will allow the use of struct types in the same way as primitive types.

**Comment by christianschmitz** [comment]
In your example you've defined an enum with three variants (newlines don't matter)

**Comment by christianschmitz** [comment]
Currently you can wrap `Buyer`:

```
enum Redeemer {
  Cancel
  Buy {
    buyer: Buyer
  }
}
```

It's a bit more verbose, but defining methods on `Buyer` can compensate for that

**Comment by christianschmitz** [comment]
(please don't get discouraged by me being a bit difficult, I'd like to continue the discussion)

**Comment by christianschmitz** [comment]
What do you think about the following: 

```
struct Buyer {
  id: PubKeyHash
  amount: Int
}

enum Redeemer {
  Cancel
  Buy {
    buyer: Buyer
  }
}

func main(redeemer: Redeemer) -> Bool {
  redeemer.switch{
    Cancel => true,
    {b: Buyer}: Buy => {...}
  }
}

// and even nested destructuring
func main(redeemer: Redeemer) -> Bool {
  redeemer.switch{
    Cancel => true,
    {{pkh: PubKeyHash, _}}: Buy => {...}
  }
}

// optional typing of intermediate structures
func main(redeemer: Redeemer) -> Bool {
  redeemer.switch{
    Cancel => true,
    {{pkh: PubKeyHash, _}: Buyer}: Buy => {...}
  }
}
```

**Comment by christianschmitz** [comment]
The same syntax could be used for function arguments and assignments:

```
func do_something_w_buyer_pkh({pkh: PubKeyHash, _}: Buyer) -> Bool {
  ...
}

// or

func do_something_w_buyer_pkh(buyer: Buyer) -> Bool {
  {pkh: PubKeyHash, amount: Int}: Buyer = buyer
}
```

**Note**: in this proposal the restructuring is positional, not field-name based

**Comment by nemo83** [comment]
* 👍 for the recursive destructuring
* 👍 as in scala, it should be _only_ positional
* 👍 I like the deconstructing in the method signature, one less declaration in the code.
* I am used to the scala syntax and I would prefer the type to be declared before the attributes Buyer(pkh: PubKeyHash, amount: Int). Not sure if there are language/framework constraints. But I can deffo get used to the type being specified after (that in fairness would follow the convention `variable: Type`.
* One request I might have, in scala there is the conditional match: `case Buyer(_: PubKeyHash, amount: Int) if amount > 0 =>`. It would be awesome if you could implement it as part of this effort.

**Comment by christianschmitz** [comment]
Type before might work. Would it be better with curly braces though (so it matches literal struct expressions)?

Let's see how it looks when mixing that with the two case syntaxes that already exist:

```
redeemer.switch{
    c: Cancel => {...},
    Buy{{pkh: PubKeyHash, _}: Buyer} => {...},
    (i: Int, _) => {...}
}
```

**Comment by christianschmitz** [comment]
And for function arguments and assignments:

```
func do_something_w_buyer_pkh(Buyer{pkh: PubKeyHash, _}, other_arg: OtherType) -> Bool {
  ...
}

// or

func do_something_w_buyer_pkh(buyer: Buyer) -> Bool {
  Buyer{pkh: PubKeyHash, amount: Int} = buyer
}
```

I feel like this works for assignments, but not so much for function arguments

**Comment by nemo83** [comment]
Thanks for the examples, it actually helps a seeing them. On a second thought. Maybe type after is better. It's more homogeneous.

Out of curiosity, if intermediate type in this case is optional `Buy{{pkh: PubKeyHash, _}} => {...},`, why is `PubKeyHash` required

**Comment by christianschmitz** [comment]
`PubKeyHash` is required so the reader knows the type of `pkh` just be looking at this code. If we allow type-inference here then the reader would have to dig deeper

**Comment by christianschmitz** [comment]
Note that this issue is only about destructuring, not about special pattern matching syntax

**Comment by nemo83** [comment]
> Note that this issue is only about destructuring, not about special pattern matching syntax

ahah ok ok got excited and carried a bit away ...

**Comment by nemo83** [comment]
> What do you think about the following:
> 
> ```
> struct Buyer {
>   id: PubKeyHash
>   amount: Int
> }
> 
> enum Redeemer {
>   Cancel
>   Buy {
>     buyer: Buyer
>   }
> }
> 
> func main(redeemer: Redeemer) -> Bool {
>   redeemer.switch{
>     Cancel => true,
>     {b: Buyer}: Buy => {...}
>   }
> }
> 
> // and even nested destructuring
> func main(redeemer: Redeemer) -> Bool {
>   redeemer.switch{
>     Cancel => true,
>     {{pkh: PubKeyHash, _}}: Buy => {...}
>   }
> }
> 
> // optional typing of intermediate structures
> func main(redeemer: Redeemer) -> Bool {
>   redeemer.switch{
>     Cancel => true,
>     {{pkh: PubKeyHash, _}: Buyer}: Buy => {...}
>   }
> }
> ```

I've just noticed on discord you're working on this, can you confirm this is the design you're following? I would be supportive of this syntax.

**Comment by christianschmitz** [comment]
I think this design is the most natural extension of the current syntax (because people would rewrite `buy: Buy` as `{buyer: Buyer}: Buy` or `{{pkh: PubKeyHash, _}}: Buy`.

I would like to get more people involved in the discussion though

**Comment by vanusquarm** [comment]
> What do you think about the following:
> 
> ```
> struct Buyer {
>   id: PubKeyHash
>   amount: Int
> }
> 
> enum Redeemer {
>   Cancel
>   Buy {
>     buyer: Buyer
>   }
> }
> 
> func main(redeemer: Redeemer) -> Bool {
>   redeemer.switch{
>     Cancel => true,
>     {b: Buyer}: Buy => {...}
>   }
> }
> 
> // and even nested destructuring
> func main(redeemer: Redeemer) -> Bool {
>   redeemer.switch{
>     Cancel => true,
>     {{pkh: PubKeyHash, _}}: Buy => {...}
>   }
> }
> 
> // optional typing of intermediate structures
> func main(redeemer: Redeemer) -> Bool {
>   redeemer.switch{
>     Cancel => true,
>     {{pkh: PubKeyHash, _}: Buyer}: Buy => {...}
>   }
> }
> ```

**Comment by vanusquarm** [comment]
Great work Christian. Love the use-cases, however, will like to discourage the introduction of nesting as seen in the last two examples as this introduced a new level of complexities such as the difficulties in tracking missing objects and subsequently the possibilities of getting many undefined errors. Eslint recently removed support for that with reason of promoting more  readable and comprehensive code.

**Comment by christianschmitz** [comment]
@vanusquarm are there any strongly typed languages that support deeply nested destructuring? (the typing would prevent undefined errors)

You might be right about the readability argument though. However, as enum variants can't yet be assigned  type directly (it has to be wrapped), this could be a convenient to restructure those variants in a single expressions

**Comment by christianschmitz** [comment]
Has been implemented in v0.13.17 of the library.

The syntax differs a bit from what was proposed above, but I think the final implementation is very consistent and conventional

https://www.hyperion-bt.org/helios-book/lang/destructuring.html

**Comment by christianschmitz** [comment]
A version of the example we've been using above using the latest version: 
```
struct Buyer {
  id: PubKeyHash
  amount: Int
}

enum Redeemer {
  Cancel
  Buy {
    buyer: Buyer
  }
}

func main(redeemer: Redeemer) -> Bool {
  redeemer.switch{
    Cancel => true,
    Buy{b} => {...}
  }
}

// and even nested destructuring
func main(redeemer: Redeemer) -> Bool {
  redeemer.switch{
    Cancel => true,
    Buy{Buyer{pkh, _}} => {...}
  }
}
```

**Comment by vanusquarm** [comment]
This is PERFECT
