### ISSUE TITLE
Retrieve Staking Hash from a StakeAddress

### ISSUE THREAD

**Issue by gavinharris-dev** [Hyperion-BT/helios#62]
The following produces `null` when it should be able to return the StakeHash

`StakeAddress.fromBech32('stake1uy5ecm28vyv5gtw68sxag4r5rwm3582q7dy8453lm2wrm0q3ckr84').stakingHash`

**Comment by gavinharris-dev** [comment]
Dirty workaround:

`StakeKeyHash.fromHex(bytesToHex(StakeAddress.fromBech32('stake1uy5ecm28vyv5gtw68sxag4r5rwm3582q7dy8453lm2wrm0q3ckr84').bytes).slice(2))`

**Comment by christianschmitz** [comment]
Thanks for calling this out. I've just released v0.12.12 which should fix this. Please take a look.
