### ISSUE TITLE
Convert Data to Struct without Error

### ISSUE THREAD

**Issue by gavinharris-dev** [Hyperion-BT/helios#68]
Be great if we could get a `Struct::from_data_safe` method where the output is an `Option[Struct]`. This will allow us to parse through for example, Reference Inputs attempting to convert the Inline Datum to the Struct data type, but not failing the transaction if the conversion fails.

The `from_data` method looks to be available for all Built In types so perhaps we could add the `from_data_safe` in all the same places? 
Something like:
`T::from_data_safe -> Option[T]`

**Comment by christianschmitz** [comment]
As discussed: should be some convenient off-chain method instead

**Comment by gavinharris-dev** [comment]
To summarize the discussion the Off Chain code should ensure that any Transaction Inputs and Reference Inputs provided will be supported within the built contract. It may be possible to produce a helper method out of perhaps the Program class that could enable a developer to 'validate' an Input Datum could be cast to the internal Builtin Plutus Type.
