### ISSUE TITLE
Opaque Value Challenging to Debug

### ISSUE THREAD

**Issue by thaddeusdiamond** [Hyperion-BT/Helios#7]
This line of code is challenging me:

```
    minting voting_ballot

    const BALLOT_BOX_PUBKEY: PubKeyHash = PubKeyHash::new(#${pubKeyHash})
    const POLLS_CLOSE: Time = Time::new(${pollsClose})
    const REFERENCE_POLICY_HASH: MintingPolicyHash = MintingPolicyHash::new(#${referencePolicyId})
    const SINGLE_NFT: Int = 1

    enum Redeemer {
      Mint
    }

    func assets_sent_to_script(tx: Tx, minted_assets: Value) -> Bool {
      print(tx.value_sent_to(BALLOT_BOX_PUBKEY).serialize().show());
      print(minted_assets.serialize().show());
      print("The line below is going to return false");
      tx.value_sent_to(BALLOT_BOX_PUBKEY).contains(minted_assets)
    }

    ...
```

The weird thing is that I am definitely only sending minted assets to this one `pubKeyHash`.  The printout I get from the trace is very challenging to debug

```
"{
 \"ScriptFailures\": {
 \"mint:0\": [
 {
 \"validatorFailed\": {
 \"error\": \"An error has occurred: User error:\
The machine terminated because of an error, either from a built-in function or from an explicit use of 'error'.\",
 \"traces\": [ 
\"a240a1401a0123aad1581c56fd93ef8ebe4c73645acadaf477716ce97339050244644cef325741a34c57696c6454616e677a203130014b57696c6454616e677a2032014b57696c6454616e677a203301\",
\"a240a14000581c139a705c0715d6a42d94e0495374ef252f78c36a286feb9f0a024342a34c57696c6454616e677a203130014b57696c6454616e677a2032014b57696c6454616e677a203301\",
 \"The line below is going to return false\"
 ]
 }
 }
 ]
 }
}"
```

Note that there is overlap in the policies but for some reason the minted assets looks like:

`a240a140`
`00581c139a705c0715d6a42d94e0495374ef252f78c36a286feb9f0a024342`
`a34c57696c6454616e677a203130014b57696c6454616e677a2032014b57696c6454616e677a203301`

That last one is the only thing I actually want to mint, I have no idea how to interpret the middle piece.  Any help would be appreciated.

**Comment by christianschmitz** [comment]
I use the following cbor tool to inspect the output of `serialize()`: https://cbor.nemo157.com

The policyId of the `value_sent_to(BALLOT_BOX_PUBKEY)` is `56fd93ef8ebe4c73645acadaf477716ce97339050244644cef325741`.

The policyId of `minted_assets` is `139a705c0715d6a42d94e0495374ef252f78c36a286feb9f0a024342`.

Both `Value`s contain `WildTangz 10`, `WildTangz 2` and `WildTangz 3`.

I feel there is circular hash problem though. The minting script depends on `REFERENCE_POLICY_HASH`, which will turn influence the actual policyId (and won't be the same as `REFERENCE_POLICY_HASH`).

I recommend a different approach where your ballot spending script checks the input tokens were also minted in the transactions.

**Comment by christianschmitz** [comment]
If you want better debugging information you can also try building and submitting the transaction using Helios. The most recent version of the library outputs an error trace whenever a RuntimeError is encountered, with line-numbers of parent calls.

**Comment by thaddeusdiamond** [comment]
Oh my god this tool is amazing! Thanks for pointing it out, I think the issue is with my JavaScript code and how I am passing in the `pubKeyHash`.  The script contract has a different `pubKeyHash` than I am referencing.  Thank you for the tool and the pointer to Helios I will definitely check out the Tx builder!
