### ISSUE TITLE
Override IS_TESTNET var: setting helios for mainnet

### ISSUE THREAD

**Issue by nemo83** [Hyperion-BT/helios#70]
Hey,

I've recently noticed that address generation is defaulted to testnet, and that makes sense to me, and that it depends on the `IS_TESTNET` var in the helios module.

Unfortunately, despite being a `var` the `IS_TESTNET` cannot be changed in `nextjs`, and I would expect to be the same in the major frontend frameworks.

Now, I think that the intent was to make the value of `IS_TESTNET` to be customised by the developer (`var` instead of `const`). So I was wondering if it was possible to wrap `IS_TESTNET` along w/ the other customiseable flag, in another object, itself declared as `const` (as it can't be overriden anyway) and that has vars inside that can be changed.

In the app I'm developing I'm seeing something similar is done by the fontawesome lib.

Example
```javascript
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
```

**Comment by christianschmitz** [comment]
v0.13.4 should fix this.

https://www.hyperion-bt.org/helios-book/api/reference/globals.html

**Comment by nemo83** [comment]
it worked. nice one and thanks as usual for the super quick fix
