### ISSUE TITLE
Wallet could not send the tx.

### ISSUE THREAD

**Issue by nemo83** [Hyperion-BT/helios#80]
After fixing the issue of the mismatching hash, I'm now encountering this when sending to script (and not when using a script).

This seems related to the the recent fix.

```json
{
    "code": 2,
    "info": "Wallet could not send the tx.",
    "message": "\"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (FromAlonzoUtxowFail (PPViewHashesDontMatch (SJust (SafeHash \\\"0000000000000000000000000000000000000000000000000000000000000000\\\")) SNothing))])\""
}
```

**Comment by christianschmitz** [comment]
v0.13.28 should fix this

**Comment by christianschmitz** [comment]
I've applied so more related fixes more recently (serializing/deserializing could allow this to happen), so v0.14.3 should definitely fix this
