### ISSUE TITLE
[Enhancement] add getters for Signature pubKey and/or pubKeyHash

### ISSUE THREAD

**Issue by rjharmon** [Hyperion-BT/helios#82]
I'm having a helios Signature, which I want to correlate to an Address, based on their pub-key-hash.  I can see the .pubKeyHash in the interface to the address.  But the Signature object, though it has a private member for the pubKey, doesn't make it available with a public (documented) accessor.  I can get to it through .dump(), but that's not documented.

Seems like there should be getters for `pubKey` and/or `pubKeyHash`

**Comment by christianschmitz** [comment]
v0.13.38 of the Helios library implements `pubKey` and `pubKeyHash` getters for the `Signature` class.

Note: `signature.pubKey` returns a `PubKey` instance which in turn wrap the raw bytes, so you can do `signature.pubKey.bytes` to get the bytes, or `signature.pubKey.hex` to get the hexadecimal representation.

**Comment by christianschmitz** [comment]
Good call!

**Comment by rjharmon** [comment]
thank you!
