### ISSUE TITLE
tx.time_range.contains() causes transaction submit error

### ISSUE THREAD

**Issue by lley154** [Hyperion-BT/helios#86]
When trying to use contains(), I got the following error:

// Check that timestamp is within valid tx
tx.time_range.contains(timestamp)

message: '"transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (ApplyTxError [UtxowFailure (UtxoFailure (FromAlonzoUtxoFail (UtxosFailure (ValidationTagMismatch (IsValid True) (FailedUnexpectedly (PlutusFailure \\"\\\\nThe 2 arg plutus script (PlutusScript PlutusV2 ScriptHash \\\\\\"e442906b23fdeb1e832f5efd8d29b87327549f3b2b3cdfcdf655c23a\\\\\\") fails.\\\\nCekError An error has occurred:  User error:\\\\nThe machine terminated part way through evaluation due to overspending the budget.\\\\nThe budget when the machine terminated was:\\\\n({ cpu: -4010\\\\n| mem: 0\\\\n})\\
...

[timerange issue.pdf](https://github.com/Hyperion-BT/helios/files/11612094/timerange.issue.pdf)

**Comment by christianschmitz** [comment]
could you check if v0.14.3 fixes this (if you have to patch the relevant change back into v0.13.38 it's really quite simple: change the last constr index in `toValidTimeRangeData` from 1 to 0:

```
toValidTimeRangeData(networkParams) {
		return new ConstrData(0, [
			new ConstrData(0, [ // LowerBound
				this.#firstValidSlot === null ? new ConstrData(0, []) : new ConstrData(1, [new IntData(networkParams.slotToTime(this.#firstValidSlot))]), // NegInf
				new ConstrData(1, []), // true
			]),
			new ConstrData(0, [ // UpperBound
				this.#lastValidSlot === null ? new ConstrData(2, []) : new ConstrData(1, [new IntData(networkParams.slotToTime(this.#lastValidSlot))]), // PosInf
				new ConstrData(0, []), // false
			]),
		]);
	}
```

**Comment by lley154** [comment]
working now - looks good!  Thank you.

https://preprod.cexplorer.io/tx/63820a50290a593eac882604159f7caedc5ec04a297f65d85c1e7a7b3bd5e293

Replaced:

(!tx.time_range.is_before(timestamp)).trace("UTP1: ") &&
(!tx.time_range.is_after(timestamp)).trace("UTP2: ") &&


With this:
 tx.time_range.contains(timestamp) &&
