### ISSUE TITLE
Getting private field must be declared in an enclosing class error while calling helios.Program.new()...

### ISSUE THREAD

**Issue by rahpal** [Hyperion-BT/Helios#9]
I am facing this issue 
private field #default must be declared in an enclosing class....
I am using nextjs app for my app
For reference:
https://github.com/rahpal/learn-cardano/tree/main/tx-apps/apps/sender-app

**Comment by christianschmitz** [comment]
Looks like I don't have access to that repo. Would it be possible to share the Helios code and Javascript that is giving the error here?

The `#default` private field is only used inside the SwitchExpr class, so I'm assuming something is going wrong with `switch` expression.

**Comment by rahpal** [comment]
I have given access to you. Just have a look

**Comment by christianschmitz** [comment]
I'm going to assume nextjs struggles with private fields named `#default` (due to default being a key-word in other contexts).

I've renamed the field to `#defaultCase`. Please try the latest version of Helios (v0.7.2) to check if that solves your problem.

**Comment by christianschmitz** [comment]
I'm also noticed that you are telling Lucid to create a transaction with a `PlutusV1` script. This should be `PlutusV2` now.

(the original Lucid example uses an outdated version of Helios).

**Comment by rahpal** [comment]
Fixed. Thanks.
