### ISSUE TITLE
Helios 15+: TypeScript: NetworkParams::timeToSlot 

### ISSUE THREAD

**Issue by gavinharris-dev** [Hyperion-BT/helios#95]
The `helios.d.ts` does not publish the:

`slotToTime(slot: bigint): bigint;` or
`timeToSlot(time: bigint): bigint;` 

Are these methods now Private in version 15?

**Comment by gavinharris-dev** [comment]
Noticed that these useful little functions are now market `@internal`. They are such useful functions that is seems a shame to hide them away and not allow developers to make use of them!

**Comment by christianschmitz** [comment]
I'll remove the @internal annotation
