### ISSUE TITLE
comments not valid inside enum variant structures

### ISSUE THREAD

**Issue by rjharmon** [Hyperion-BT/helios#99]
Was this intentional?

```
enum Foo {
  // comment ok here
  Bar 
  Buz {
   // not ok here
  }
}
```

**Comment by christianschmitz** [comment]
`Buz` can't be empty. What exactly is the error message thrown by the compiler?

**Comment by rjharmon** [comment]
Sorry for leaving this dangling.  Seems to be resolved in a recent version.  

My editor still shows the inner comment as funky, but the compiler isn't throwing.  Probably I just need to update my editor plugin.
